apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plexserver
  name: plexserver
  namespace: plex
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: plexserver
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: plexserver
    spec:
      volumes:
        - name: nfs-data
          persistentVolumeClaim:
            claimName: plex-pvc-data
      containers:
        - env:
            - name: PLEX_CLAIM
              value: claim-C-xxxxxxxxxxxxxxxxxx
            - name: PGID
              value: '101'
            - name: PUID
              value: '1001'
            - name: VERSION
              value: latest
            - name: TZ
              value: America/Toronto
          image: ghcr.io/linuxserver/plex
          imagePullPolicy: Always
          name: plexserver
          ports:
            - containerPort: 32400
              name: pms-web
              protocol: TCP
            - containerPort: 32469
              name: dlna-tcp
              protocol: TCP
            - containerPort: 1900
              name: dlna-udp
              protocol: UDP
            - containerPort: 3005
              name: plex-companion
              protocol: TCP
            - containerPort: 5353
              name: discovery-udp
              protocol: UDP
            - containerPort: 8324
              name: plex-roku
              protocol: TCP
            - containerPort: 32410
              name: gdm-32410
              protocol: UDP
            - containerPort: 32412
              name: gdm-32412
              protocol: UDP
            - containerPort: 32413
              name: gdm-32413
              protocol: UDP
            - containerPort: 32414
              name: gdm-32414
              protocol: UDP
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /data
              name: nfs-data
            - mountPath: /config
              name: nfs-data
              subPath: "Plex/config"
      restartPolicy: Always

